const ScheduledTaskActionTypes = {
    SET_SCHEDULED_TASKS: 'SET_SCHEDULED_TASKS',
    ADD_SCHEDULED_TASK: 'ADD_SCHEDULED_TASK',
    UPDATE_SCHEDULED_TASK: 'UPDATE_SCHEDULED_TASK',
    DELETE_SCHEDULED_TASK: 'DELETE_SCHEDULED_TASK'
}

export default ScheduledTaskActionTypes;