const BestPracticeActionTypes = {
    SET_SINGLE_BEST_PRACTICE: 'SET_SINGLE_BEST_PRACTICE',
    SET_BEST_PRACTICES: 'SET_BEST_PRACTICES',
    ADD_BEST_PRACTICE: 'ADD_BEST_PRACTICE',
    UPDATE_BEST_PRACTICES: 'UPDATE_BEST_PRACTICES',
    DELETE_BEST_PRACTICE: 'DELETE_BEST_PRACTICE'

};

export default BestPracticeActionTypes;