const EmployeeActionTypes = {
    SET_SINGLE_EMPLOYEE: 'SET_SINGLE_EMPLOYEE',
    SET_EMPLOYEES: 'SET_EMPLOYEES',
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE'
}

export default EmployeeActionTypes;