const DepartmentActionTypes = {
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
    SET_DEPARTMENT: 'SET_DEPARTMENT',
    SET_ALL_DEPARTMENTS: 'SET_ALL_DEPARTMENTS',

};

export default DepartmentActionTypes;