const DepartmentActionTypes = {
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
    FETCH_DEPARTMENT: 'FETCH_DEPARTMENT',
    FETCH_ALL_DEPARTMENTS: 'FETCH_ALL_DEPARTMENTS',
    
};

export default DepartmentActionTypes;