const DepartmentActionTypes = {
    SET_SINGLE_DEPARTMENT: 'SET_DEPARTMENT',
    SET_DEPARTMENTS: 'SET_ALL_DEPARTMENTS',
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    DELETE_DEPARTMENT: 'DELETE_DEPARTMENT'

};

export default DepartmentActionTypes;